language: r
sudo: required
dist: trusty
cache:
  packages: true
  directories:
  - $HOME/usr/local
warnings_are_errors: true
before_install:
  - curl -OL https://raw.githubusercontent.com/jefferis/nat/master/build-cmtk.sh
  - bash build-cmtk.sh
before_script:
  - export PATH=$PATH:$HOME/usr/local/bin
r_binary_packages:
  - rgl
  - RANN
  - igraph
  - filehash
  - digest
  - testthat
  - RCurl
  - stringi
  - stringr
env:
  global:
    - RGL_USE_NULL=TRUE
